apiVersion: v1
kind: Namespace
metadata:
  name: k8s-watchdog
  labels:
    'kubesphere.io/namespace': 'k8s-watchdog'
    'kubesphere.io/workspace': 'cloud-platform'
# kubectl create secret docker-registry harbor --docker-server=harbor.bluemoon.com.cn --docker-username=deploy --docker-password=Harbor@bm123 --docker-email=xuxianxue@bluemoon.com.cn
# kubectl get secret harbor --output=yaml
#---
# dev
#apiVersion: v1
#data:
#  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuYmx1ZW1vb24uY29tLmNuIjp7InVzZXJuYW1lIjoiZGVwbG95IiwicGFzc3dvcmQiOiJIYXJib3JAYm0xMjMiLCJlbWFpbCI6Inh1eGlhbnh1ZUBibHVlbW9vbi5jb20uY24iLCJhdXRoIjoiWkdWd2JHOTVPa2hoY21KdmNrQmliVEV5TXc9PSJ9fX0=
#kind: Secret
#metadata:
#  managedFields:
#    - apiVersion: v1
#      fieldsType: FieldsV1
#      fieldsV1:
#        f:data:
#          .: {}
#          f:.dockerconfigjson: {}
#        f:type: {}
#      manager: kubectl
#      operation: Update
#      time: "2021-06-16T02:47:47Z"
#  name: harbor
#  namespace: k8s-watchdog
#type: kubernetes.io/dockerconfigjson
---
# test
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IuYmx1ZW1vb24uY29tLmNuIjp7InVzZXJuYW1lIjoiZGVwbG95IiwicGFzc3dvcmQiOiJIYXJib3JAYm0xMjMiLCJlbWFpbCI6Inh1eGlhbnh1ZUBibHVlbW9vbi5jb20uY24iLCJhdXRoIjoiWkdWd2JHOTVPa2hoY21KdmNrQmliVEV5TXc9PSJ9fX0=
kind: Secret
metadata:
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:.dockerconfigjson: {}
        f:type: {}
      manager: kubectl
      operation: Update
      time: "2021-06-18T02:32:39Z"
  name: harbor
  namespace: k8s-watchdog
type: kubernetes.io/dockerconfigjson
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: k8s-watchdog
  namespace: k8s-watchdog
spec:
  template:
    metadata:
      labels:
        app: k8s-watchdog
      name: k8s-watchdog
    spec:
      imagePullSecrets:
        - name: harbor
      containers:
        - name: k8s-watchdog-pod
          imagePullPolicy: Always
          image: harbor.bluemoon.com.cn/cloud-platform/k8s-watchdog:v3
          volumeMounts:
            - mountPath: /root/.kube
              name: kube-manage
            - mountPath: /var/log/containers
              name: pod-log-dir
            - mountPath: /var/lib/docker/containers
              name: docker-log-dir
            - mountPath: /etc/hosts
              name: host-dns
            - mountPath: /etc/localtime
              name: timezone
          env:
            - name: ENABLE_K8S
              value: 'true'
            - name: ES_URLS
              value: 'http://192.168.63.7:9200,http://192.168.63.8:9200,http://192.168.63.9:9200'
            - name: ES_USERNAME
              value: 'elastic'
            - name: ES_PASSWORD
              value: 'GoodEsDbStar'
            - name: MYSQL_URLS
              value: '192.168.32.46:3306'
            - name: MYSQL_USERNAME
              value: 'app_monitor'
            - name: MYSQL_PASSWORD
              value: 'all8^#XAGRu8O'
            - name: CONF_CONSUMER_FILE_PATH
              value: '/data/watchdog/watchdog-cloud-bin/resources/client-pro.yml'
      volumes:
        - name: kube-manage
          hostPath:
            path: /root/.kube
        - name: pod-log-dir
          hostPath:
            path: /var/log/containers
        - name: docker-log-dir
          hostPath:
            path: /var/lib/docker/containers
        - name: host-dns
          hostPath:
            path: /etc/hosts
        - name: timezone
          hostPath:
            path: /etc/localtime
  selector:
    matchLabels:
      app: k8s-watchdog
